codes = {}

codes['a_z'] = [
    {'id':'a', 'code':97},
    {'id':'b', 'code':98},
    {'id':'c', 'code':99},
    {'id':'d', 'code':100},
    {'id':'e', 'code':101},
    {'id':'f', 'code':102},
    {'id':'g', 'code':103},
    {'id':'h', 'code':104},
    {'id':'i', 'code':105},
    {'id':'j', 'code':106},
    {'id':'k', 'code':107},
    {'id':'l', 'code':108},
    {'id':'m', 'code':109},
    {'id':'n', 'code':110},
    {'id':'o', 'code':111},
    {'id':'p', 'code':112},
    {'id':'q', 'code':113},
    {'id':'r', 'code':114},
    {'id':'s', 'code':115},
    {'id':'t', 'code':116},
    {'id':'u', 'code':117},
    {'id':'v', 'code':118},
    {'id':'w', 'code':119},
    {'id':'x', 'code':120},
    {'id':'y', 'code':121},
    {'id':'z', 'code':122}
]

codes['A_Z'] = [
    {'id':'A', 'code':65},
    {'id':'B', 'code':66},
    {'id':'C', 'code':67},
    {'id':'D', 'code':68},
    {'id':'E', 'code':69},
    {'id':'F', 'code':70},
    {'id':'G', 'code':71},
    {'id':'H', 'code':72},
    {'id':'I', 'code':73},
    {'id':'J', 'code':74},
    {'id':'K', 'code':75},
    {'id':'L', 'code':76},
    {'id':'M', 'code':77},
    {'id':'N', 'code':78},
    {'id':'O', 'code':79},
    {'id':'P', 'code':80},
    {'id':'Q', 'code':81},
    {'id':'R', 'code':82},
    {'id':'S', 'code':83},
    {'id':'T', 'code':84},
    {'id':'U', 'code':85},
    {'id':'V', 'code':86},
    {'id':'W', 'code':87},
    {'id':'X', 'code':88},
    {'id':'Y', 'code':89},
    {'id':'Z', 'code':90}
]

codes['num'] = [
    {'id': '0', 'code': 48 },
    {'id': '1', 'code': 49 },
    {'id': '2', 'code': 50 },
    {'id': '3', 'code': 51 },
    {'id': '4', 'code': 52 },
    {'id': '5', 'code': 53 },
    {'id': '6', 'code': 54 },
    {'id': '7', 'code': 55 },
    {'id': '8', 'code': 56 },
    {'id': '9', 'code': 57 }
]

codes['xx'] = [
    {'id':'[', 'code':91},
    {'id':']', 'code':93},
    {'id':'{', 'code':123},
    {'id':'}', 'code':125},
    {'id':' ', 'code':32},
    {'id':'.', 'code':46},
    {'id':'(', 'code':40},
    {'id':')', 'code':41},
    {'id':'/', 'code':47},
    {'id':'"', 'code':34},
    {'id':"'", 'code':39},
    {'id':'@', 'code':64},
    {'id':'#', 'code':35},
    {'id':'$', 'code':36},
    {'id':'%', 'code':37},
    {'id':'^', 'code':94},
    {'id':'&', 'code':38},
    {'id':'*', 'code':42},
    {'id':'=', 'code':61},
    {'id':'+', 'code':43},
    {'id':'-', 'code':45},
    {'id':'_', 'code':95},
    {'id':';', 'code':59},
    {'id':':', 'code':58},
    {'id':'<', 'code':60},
    {'id':'>', 'code':62},
    {'id':',', 'code':44},
    {'id':'?', 'code':63},
    {'id':'~', 'code':126},
]

